var classes = [
    {
        "name": "ServerPlanning\\ServerPlanning",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "ServerPlanning\\Server",
            "Exception",
            "ServerPlanning\\ServerAllocationFirstFitStrategy"
        ],
        "parents": [],
        "lcom": 1,
        "length": 21,
        "vocabulary": 11,
        "volume": 72.65,
        "difficulty": 4.29,
        "effort": 311.35,
        "level": 0.23,
        "bugs": 0.02,
        "time": 17,
        "intelligentContent": 16.95,
        "number_operators": 6,
        "number_operands": 15,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 18,
        "loc": 36,
        "lloc": 18,
        "mi": 103.5,
        "mIwoC": 59.05,
        "commentWeight": 44.46,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "package": "ServerPlanning\\",
        "pageRank": 0.05,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\Server",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCpu",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCpu",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRam",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRam",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHdd",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setHdd",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateResource",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 3,
        "wmc": 9,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ServerPlanning\\ServerSpecifications",
            "self",
            "self",
            "self",
            "ServerPlanning\\Exceptions\\InvalidResourceException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 47,
        "vocabulary": 16,
        "volume": 188,
        "difficulty": 4.04,
        "effort": 759.23,
        "level": 0.25,
        "bugs": 0.06,
        "time": 42,
        "intelligentContent": 46.55,
        "number_operators": 12,
        "number_operands": 35,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 97,
        "loc": 142,
        "lloc": 45,
        "mi": 95.65,
        "mIwoC": 47.74,
        "commentWeight": 47.91,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 20,
        "totalSystemComplexity": 28,
        "package": "ServerPlanning\\",
        "pageRank": 0.12,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\ServerAllocationFirstFitStrategy",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "ServerPlanning\\ServerAllocationStrategy",
            "ServerPlanning\\Server",
            "ServerPlanning\\VirtualMachine"
        ],
        "parents": [],
        "lcom": 1,
        "length": 52,
        "vocabulary": 14,
        "volume": 197.98,
        "difficulty": 16,
        "effort": 3167.72,
        "level": 0.06,
        "bugs": 0.07,
        "time": 176,
        "intelligentContent": 12.37,
        "number_operators": 20,
        "number_operands": 32,
        "number_operators_unique": 7,
        "number_operands_unique": 7,
        "cloc": 42,
        "loc": 69,
        "lloc": 27,
        "mi": 98.91,
        "mIwoC": 52.16,
        "commentWeight": 46.76,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 9.75,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 19.5,
        "package": "ServerPlanning\\",
        "pageRank": 0.08,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\VirtualMachine",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCpu",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCpu",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRam",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRam",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHdd",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setHdd",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateResource",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 3,
        "wmc": 9,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ServerPlanning\\ServerSpecifications",
            "self",
            "self",
            "self",
            "ServerPlanning\\Exceptions\\InvalidResourceException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 47,
        "vocabulary": 16,
        "volume": 188,
        "difficulty": 4.04,
        "effort": 759.23,
        "level": 0.25,
        "bugs": 0.06,
        "time": 42,
        "intelligentContent": 46.55,
        "number_operators": 12,
        "number_operands": 35,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 97,
        "loc": 142,
        "lloc": 45,
        "mi": 95.65,
        "mIwoC": 47.74,
        "commentWeight": 47.91,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 20,
        "totalSystemComplexity": 28,
        "package": "ServerPlanning\\",
        "pageRank": 0.27,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\Exceptions\\InvalidResourceException",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "parent"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 1,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 0,
        "effort": 0,
        "level": 1.43,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 7,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 71.69,
        "mIwoC": 71.69,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "ServerPlanning\\Exceptions\\",
        "pageRank": 0.19,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    }
]